services:
  api-gateway:
    build:
      context: ./Backend/api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    networks:
      - medicine-network

  user-service:
    build:
      context: ./Backend/user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://hoi321668_db_user:ppessWAOiuSL2lys@medicine.g3veeqn.mongodb.net/db_users?appName=medicine
      - JWT_SECRET=SmartMedicineShop_JWT_Secret_2024
      - PORT=3001
      - CLOUDINARY_URL=cloudinary://273856488716346:aRGu_t97a3MGOYuDGrtT1iXKfac@dr7blo9il
      - CLOUDINARY_CLOUD_NAME=dr7blo9il
      - CLOUDINARY_API_KEY=273856488716346
      - CLOUDINARY_API_SECRET=aRGu_t97a3MGOYuDGrtT1iXKfac
    networks:
      - medicine-network

  product-service:
    build:
      context: ./Backend/product-service
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb+srv://hoi321668_db_user:ppessWAOiuSL2lys@medicine.g3veeqn.mongodb.net/db_products?appName=medicine
      - PORT=3002
    networks:
      - medicine-network

  order-service:
    build:
      context: ./Backend/order-service
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb+srv://hoi321668_db_user:ppessWAOiuSL2lys@medicine.g3veeqn.mongodb.net/db_orders?appName=medicine
      - JWT_SECRET=SmartMedicineShop_JWT_Secret_2024
      - PORT=3003
      - CLOUDINARY_URL=cloudinary://273856488716346:aRGu_t97a3MGOYuDGrtT1iXKfac@dr7blo9il
      - CLOUDINARY_CLOUD_NAME=dr7blo9il
      - CLOUDINARY_API_KEY=273856488716346
      - CLOUDINARY_API_SECRET=aRGu_t97a3MGOYuDGrtT1iXKfac
    networks:
      - medicine-network

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    networks:
      - medicine-network

  admin:
    build:
      context: ./Admin
    container_name: admin
    ports:
      - "5174:5174"
    env_file:
      - ./Admin/.env
    networks:
      - medicine-network

networks:
  medicine-network:
    driver: bridge
